Update Jenkinsfile-lab7

diff --git a/Jenkinsfile-lab7 b/Jenkinsfile-lab7
--- a/Jenkinsfile-lab7
+++ b/Jenkinsfile-lab7
@@ -18,17 +18,26 @@ stages {
     stage('Run Container') {
         steps {
             sh '''
+            docker rm -f $CONTAINER_NAME || true
             docker run -d -p 8000:8000 --name $CONTAINER_NAME $IMAGE_NAME
             '''
         }
     }
 
-    stage('Wait for Service') {
+    stage('Wait for Service Readiness') {
         steps {
             sh '''
             echo "Waiting for API..."
-            sleep 10
-            curl --fail http://localhost:8000/docs
+            for i in {1..15}; do
+                if curl -s http://host.docker.internal:8000/docs > /dev/null; then
+                    echo "API is ready"
+                    exit 0
+                fi
+                echo "Waiting..."
+                sleep 2
+            done
+            echo "API failed to start"
+            exit 1
             '''
         }
     }
@@ -39,15 +48,15 @@ stages {
 
                 def response = sh(
                     script: '''
-                    curl -s "http://localhost:8000/predict?fixed_acidity=7.4&volatile_acidity=0.70&citric_acid=0.0&residual_sugar=1.9&chlorides=0.076&free_sulfur_dioxide=11&total_sulfur_dioxide=34&density=0.9978&pH=3.51&sulphates=0.56&alcohol=9.4"
+                    curl -s "http://host.docker.internal:8000/predict?fixed_acidity=7.4&volatile_acidity=0.70&citric_acid=0.0&residual_sugar=1.9&chlorides=0.076&free_sulfur_dioxide=11&total_sulfur_dioxide=34&density=0.9978&ph=3.51&sulphates=0.56&alcohol=9.4"
                     ''',
                     returnStdout: true
                 ).trim()
 
                 echo "API Response: ${response}"
 
-                if (!response.contains("prediction")) {
-                    error("Prediction field missing!")
+                if (!response.contains("wine_quality")) {
+                    error("wine_quality field missing in response")
                 }
             }
         }
@@ -58,14 +67,14 @@ stages {
             script {
 
                 def response = sh(
-                    script: 'curl -s "http://localhost:8000/predict"',
+                    script: 'curl -s "http://host.docker.internal:8000/predict"',
                     returnStdout: true
                 ).trim()
 
                 echo "Invalid Response: ${response}"
 
                 if (!response.contains("detail")) {
-                    error("Invalid request was not handled correctly")
+                    error("Invalid request not handled correctly")
                 }
             }
         }
