Update Jenkinsfile-lab7

diff --git a/Jenkinsfile-lab7 b/Jenkinsfile-lab7
--- a/Jenkinsfile-lab7
+++ b/Jenkinsfile-lab7
@@ -1,80 +1,85 @@
 pipeline {
-    agent any
+agent any
 
-    environment {
-        IMAGE_NAME = "2022bcs0184manoj/2022bcs0184-lab6"
-        CONTAINER_NAME = "ml-test-container"
-    }
+```
+environment {
+    IMAGE_NAME = "2022bcs0184manoj/2022bcs0184-lab6"
+    CONTAINER_NAME = "ml-test-container"
+}
 
-    stages {
+stages {
 
-        stage('Pull Image') {
-            steps {
-                sh 'sudo docker pull $IMAGE_NAME'
-            }
-        }
-
-        stage('Run Container') {
-            steps {
-                sh '''
-                sudo docker run -d -p 8000:8000 --name $CONTAINER_NAME $IMAGE_NAME
-                '''
-            }
-        }
-
-        stage('Wait for Service') {
-            steps {
-                sh '''
-                echo "Waiting for API..."
-                sleep 10
-                curl --fail http://localhost:8000/docs
-                '''
-            }
-        }
-
-        stage('Send Valid Inference Request') {
-            steps {
-                script {
-                    def response = sh(
-                        script: '''
-                        curl -s "http://localhost:8000/predict?fixed_acidity=7.4&volatile_acidity=0.70&citric_acid=0.0&residual_sugar=1.9&chlorides=0.076&free_sulfur_dioxide=11&total_sulfur_dioxide=34&density=0.9978&pH=3.51&sulphates=0.56&alcohol=9.4"
-                        ''',
-                        returnStdout: true
-                    ).trim()
-
-                    echo "API Response: ${response}"
-
-                    if (!response.contains("prediction")) {
-                        error("Prediction field missing!")
-                    }
-                }
-            }
-        }
-
-        stage('Send Invalid Request') {
-            steps {
-                script {
-                    def response = sh(
-                        script: 'curl -s "http://localhost:8000/predict"',
-                        returnStdout: true
-                    ).trim()
-
-                    echo "Invalid Response: ${response}"
-
-                    if (!response.contains("detail")) {
-                        error("Invalid request was not handled correctly")
-                    }
-                }
-            }
+    stage('Pull Image') {
+        steps {
+            sh 'docker pull $IMAGE_NAME'
         }
     }
 
-    post {
-        always {
+    stage('Run Container') {
+        steps {
             sh '''
-            sudo docker stop $CONTAINER_NAME || true
-            sudo docker rm $CONTAINER_NAME || true
+            docker run -d -p 8000:8000 --name $CONTAINER_NAME $IMAGE_NAME
             '''
         }
     }
+
+    stage('Wait for Service') {
+        steps {
+            sh '''
+            echo "Waiting for API..."
+            sleep 10
+            curl --fail http://localhost:8000/docs
+            '''
+        }
+    }
+
+    stage('Send Valid Inference Request') {
+        steps {
+            script {
+
+                def response = sh(
+                    script: '''
+                    curl -s "http://localhost:8000/predict?fixed_acidity=7.4&volatile_acidity=0.70&citric_acid=0.0&residual_sugar=1.9&chlorides=0.076&free_sulfur_dioxide=11&total_sulfur_dioxide=34&density=0.9978&pH=3.51&sulphates=0.56&alcohol=9.4"
+                    ''',
+                    returnStdout: true
+                ).trim()
+
+                echo "API Response: ${response}"
+
+                if (!response.contains("prediction")) {
+                    error("Prediction field missing!")
+                }
+            }
+        }
+    }
+
+    stage('Send Invalid Request') {
+        steps {
+            script {
+
+                def response = sh(
+                    script: 'curl -s "http://localhost:8000/predict"',
+                    returnStdout: true
+                ).trim()
+
+                echo "Invalid Response: ${response}"
+
+                if (!response.contains("detail")) {
+                    error("Invalid request was not handled correctly")
+                }
+            }
+        }
+    }
+}
+
+post {
+    always {
+        sh '''
+        docker stop $CONTAINER_NAME || true
+        docker rm $CONTAINER_NAME || true
+        '''
+    }
+}
+```
+
 }
